name: 'Setup Elasticsearch with Plugins'
description: 'Github action to setup elasticsearch with plugins '
author: 'everpcpc'

branding:
    icon: 'database'
    color: 'green'

inputs:
    version:
      description: 'The version of the Elasticsearch you want to run'
      required: true
    plugins:
        description: 'Plugins to install before start'
        required: false

runs:
    using: 'node12'
    main: 'run.js'
